<?php

/**
 * @file
 * Contains json2node.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function json2node_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the json2node module.
    case 'help.page.json2node':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Woopity do') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function json2node_theme() {
  return [
    'json2node' => [
      'render element' => 'children',
    ],
  ];
}
